# Generated by Django 5.2.16 on 2026-07-25 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('timezone', models.CharField(default='Europe/Copenhagen', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=16)),
            ],
            options={
                'ordering': ['-year'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='events_eventyear_dates_ordered')],
            },
        ),
    ]
