# Generated by Django 5.2.16 on 2026-07-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventyear',
            name='status',
            field=models.CharField(choices=[('draft', 'Kladde'), ('active', 'Aktiv'), ('completed', 'Afsluttet'), ('archived', 'Arkiveret')], default='draft', max_length=16),
        ),
    ]
