# Generated by Django 5.2.16 on 2026-07-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventyear_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventyear',
            options={'ordering': ['-year'], 'verbose_name': 'eventår', 'verbose_name_plural': 'eventår'},
        ),
    ]
