# Generated by Django 5.2.16 on 2026-07-26 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventyear_options'),
        ('people', '0004_alter_eventparticipation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=2000)),
                ('activity_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_time_approximate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('event_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventyear')),
                ('owner_participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_activities', to='people.eventparticipation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aktivitet',
                'verbose_name_plural': 'aktiviteter',
                'ordering': ['activity_date', 'start_time', 'pk'],
                'indexes': [models.Index(fields=['event_year', 'activity_date', 'start_time'], name='events_acti_event_y_83206f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='events_activity_end_time_after_start_time')],
            },
        ),
    ]
