# Generated by Django 5.2.16 on 2026-07-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('people', '0002_alter_eventparticipation_event_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_digest', models.CharField(max_length=64, unique=True)),
                ('window_started_at', models.DateTimeField()),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='invitation',
            name='accounts_in_expires_64ed97_idx',
        ),
        migrations.AddField(
            model_name='invitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['expires_at', 'used_at', 'revoked_at'], name='accounts_in_expires_24d5c9_idx'),
        ),
    ]
