# Generated by Django 5.2.16 on 2026-07-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitationthrottle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='purpose',
            field=models.CharField(choices=[('create_account', 'Opret konto'), ('reset_credentials', 'Nulstil adgangskode')], max_length=32),
        ),
    ]
