# Generated by Django 5.2.16 on 2026-07-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_invitation_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'invitation', 'verbose_name_plural': 'invitationer'},
        ),
        migrations.AlterModelOptions(
            name='invitationthrottle',
            options={'verbose_name': 'invitationsbeskyttelse', 'verbose_name_plural': 'invitationsbeskyttelser'},
        ),
        migrations.AlterModelOptions(
            name='loginthrottle',
            options={'verbose_name': 'loginbeskyttelse', 'verbose_name_plural': 'loginbeskyttelser'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'bruger', 'verbose_name_plural': 'brugere'},
        ),
    ]
