# Generated by Django 5.2.16 on 2026-07-25 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventyear')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventyear')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.household')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_membership', to='people.eventparticipation')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('age_group', models.CharField(choices=[('0_3', '0-3'), ('4_11', '4-11'), ('12_18', '12-18'), ('adult', 'Adult')], max_length=16)),
                ('login_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.participant'),
        ),
        migrations.CreateModel(
            name='EventRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('event_organizer', 'Event organizer'), ('chore_coordinator', 'Chore coordinator'), ('food_coordinator', 'Food coordinator'), ('adult_participant', 'Adult participant'), ('teen_participant', 'Teen participant')], max_length=32)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='people.eventparticipation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participation', 'role'), name='people_role_unique_participation_role')],
            },
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.UniqueConstraint(fields=('event_year', 'name'), name='people_household_unique_event_name'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipation',
            constraint=models.UniqueConstraint(fields=('event_year', 'participant'), name='people_participation_unique_event_participant'),
        ),
    ]
