# Generated by Django 5.2.16 on 2026-07-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='event_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventyear'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.participant'),
        ),
        migrations.AlterField(
            model_name='household',
            name='event_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventyear'),
        ),
    ]
