# Generated by Django 5.2.16 on 2026-07-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_eventparticipation_event_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventroleassignment',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('event_organizer', 'Eventansvarlig'), ('chore_coordinator', 'Opgaveansvarlig'), ('food_coordinator', 'Madansvarlig'), ('adult_participant', 'Voksen deltager'), ('teen_participant', 'Teenagedeltager')], max_length=32),
        ),
    ]
