# Generated by Django 5.2.16 on 2026-07-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_eventroleassignment_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventparticipation',
            options={'verbose_name': 'eventdeltagelse', 'verbose_name_plural': 'eventdeltagelser'},
        ),
        migrations.AlterModelOptions(
            name='eventroleassignment',
            options={'verbose_name': 'eventrolle', 'verbose_name_plural': 'eventroller'},
        ),
        migrations.AlterModelOptions(
            name='household',
            options={'verbose_name': 'husstand', 'verbose_name_plural': 'husstande'},
        ),
        migrations.AlterModelOptions(
            name='householdmembership',
            options={'verbose_name': 'husstandsmedlemskab', 'verbose_name_plural': 'husstandsmedlemskaber'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'deltager', 'verbose_name_plural': 'deltagere'},
        ),
    ]
