# Generated by Django 5.2.16 on 2026-07-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_event_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
