# Generated by Django 5.2.16 on 2026-07-25 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('notifications', '0003_notificationdelivery_claimed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='idempotency_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('event_year', 'recipient', 'idempotency_key'), name='notifications_unique_recipient_event_idempotency'),
        ),
    ]
