# Generated by Django 5.2.16 on 2026-07-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Afventer'), ('processing', 'Behandles'), ('sent', 'Sendt'), ('retry', 'Prøv igen'), ('failed', 'Mislykkedes')], default='pending', max_length=16),
        ),
    ]
