# Generated by Django 5.2.16 on 2026-07-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationdelivery_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notifikation', 'verbose_name_plural': 'notifikationer'},
        ),
        migrations.AlterModelOptions(
            name='notificationdelivery',
            options={'verbose_name': 'notifikationslevering', 'verbose_name_plural': 'notifikationsleveringer'},
        ),
        migrations.AlterModelOptions(
            name='notificationstate',
            options={'verbose_name': 'notifikationsstatus', 'verbose_name_plural': 'notifikationsstatusser'},
        ),
    ]
